# Generated by Django 4.2.5 on 2023-10-24 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        # specify any dependencies here
    ]

    operations = [
        # specify any database operations here
    ]
