# Generated by Django 4.2.5 on 2023-11-19 10:45

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adType', models.CharField(choices=[('100A', '100A'), ('100B', '100B'), ('100C', '100C'), ('100F', '100F'), ('100G', '100G'), ('100H', '100H')], max_length=80, verbose_name='نوع تبلیغ')),
                ('brandName', models.CharField(max_length=80, verbose_name='نام برند')),
                ('brandLink', models.URLField(verbose_name='لینک برند')),
                ('adFile', models.FileField(help_text='Uploaded file must be .gif or .jpg', upload_to='filetype/', validators=[django.core.validators.FileExtensionValidator(['gif', 'jpg'])], verbose_name='فایل تبلیغ')),
                ('textAd', models.TextField(verbose_name='متن تبلیغ')),
                ('isTextAd', models.BooleanField(default=False)),
                ('startsDate', models.DateField(verbose_name='تاریخ شروع تبلیغ')),
                ('endsDate', models.DateField(verbose_name='تاریخ پایان تبلیغ')),
                ('shouldDelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
        migrations.CreateModel(
            name='albumPlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.CharField(max_length=70, verbose_name='پلتفرم')),
            ],
            options={
                'verbose_name': 'پلتفرم آلبوم',
                'verbose_name_plural': 'پلتفرم آلبوم ها',
            },
        ),
        migrations.CreateModel(
            name='albumsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumTags', models.CharField(max_length=70, verbose_name='تگ آلبوم')),
            ],
            options={
                'verbose_name': 'تگ آلبوم',
                'verbose_name_plural': 'تگ های آلبوم',
            },
        ),
        migrations.CreateModel(
            name='allPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('image', models.ImageField(help_text=' Image file must be lowerthan 200kb, preferably 100kb , Use it in WEBP format, and trasparent', null=True, upload_to='images/', verbose_name='تصویر تک صفحه ')),
                ('platforms', models.CharField(blank=True, choices=[('PC', 'PC'), ('android', 'android'), ('IOS', 'ios'), ('xbox', 'xbox'), ('playStation', 'playstation'), ('others', 'others')], max_length=30, null=True, verbose_name='پلتفرم')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('eventStage', models.CharField(blank=True, choices=[('E3', 'E3'), ('gameAwards', 'gameAwards'), ('blizzCon', 'blizzCon'), ('gamesCom', 'gamesCom'), ('tokyoGameShow', 'tokyoGameShow')], max_length=40, null=True, verbose_name='برگزارکننده رویداد')),
                ('videoType', models.CharField(blank=True, choices=[('gameplays', 'gamePlays'), ('trailers', 'trailers'), ('blink', 'blink')], max_length=40, null=True, verbose_name='تایپ ویدیو')),
                ('isEvent', models.BooleanField(default=False, null=True)),
                ('isArticle', models.BooleanField(default=False, null=True)),
                ('isVideo', models.BooleanField(default=False, null=True)),
                ('isNews', models.BooleanField(default=False, null=True)),
                ('isStory', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'جدول پست ها',
                'verbose_name_plural': 'جدول همه پست ها',
            },
        ),
        migrations.CreateModel(
            name='allPostsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTags', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ های جدول اصلی',
            },
        ),
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=60, verbose_name='نام')),
                ('username', models.SlugField(null=True, verbose_name='آدرس')),
                ('about', models.TextField(default='', verbose_name='درباره نویسنده')),
                ('avatar', models.ImageField(default='', help_text='avatar file must be lowerthan 100kb and maximum size is : 300*300 pixels', upload_to='', verbose_name='آواتار')),
                ('expertise', models.CharField(blank=True, choices=[('programmer', 'برنامه نویس'), ('contentCreator', 'تولید کننده محتوا'), ('seoExpert', 'کارشناس سئو'), ('designer', 'طراح'), ('marketer', 'بازاریاب'), ('gamer', 'گیمر'), ('gameDesigner', 'طراح بازی'), ('graphist', 'گرافیست'), ('softWareExpert', 'کارشناس نرم افزار'), ('hardWareExpert', 'کارشناس سخت افزار')], max_length=30, null=True, verbose_name='حوزه فعالیت')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان ',
            },
        ),
        migrations.CreateModel(
            name='bazi100Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('developer', 'developer'), ('author', 'author'), ('advertisement', 'advertisement'), ('cameraman', 'cameraman'), ('soicials', 'socials')], max_length=80, null=True, verbose_name='سمت')),
                ('memberName', models.CharField(max_length=80, verbose_name='اسم کاربر')),
                ('expertise', models.CharField(choices=[('programmer', 'برنامه نویس'), ('contentCreator', 'تولید کننده محتوا'), ('seoExpert', 'کارشناس سئو'), ('designer', 'طراح'), ('marketer', 'بازاریاب'), ('gamer', 'گیمر'), ('gameDesigner', 'طراح بازی'), ('graphist', 'گرافیست'), ('softWareExpert', 'کارشناس نرم افزار'), ('hardWareExpert', 'کارشناس سخت افزار')], max_length=70, verbose_name='حرفه')),
                ('username', models.CharField(help_text="Usernames can contain letters(a-z),numbers(0-9),and periods(.).Usernames cannot contain an ampersand(&),equals sings(=),underscore(_),aposterophe('),dash(-),plus sign(+),comma(,),brackets(<,>),or more than one period(.) in a row", max_length=80, verbose_name='نام کاربری')),
                ('avatar', models.ImageField(help_text='Avatar file must be lowerthan 100kb and maximum size is : 300*300 pixels', null=True, upload_to='images/', verbose_name='آواتار')),
                ('linkedin', models.CharField(max_length=80, verbose_name='لینکدین')),
                ('instagram', models.CharField(max_length=80, verbose_name='اینستاگرام')),
                ('twitter', models.CharField(max_length=80, verbose_name='توییتر')),
                ('email', models.EmailField(max_length=80, verbose_name='ایمیل')),
                ('about', models.TextField(verbose_name='درباره')),
            ],
            options={
                'verbose_name': 'تیم بازی 100',
                'verbose_name_plural': 'تیم بازی 100',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(verbose_name='متن کامنت')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='زمان و تاریخ انتشار کامنت')),
                ('likeCount', models.IntegerField(default=0, verbose_name='تعداد لایک\u200cها')),
                ('commentReply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comments', verbose_name='ریپلای')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.allposts', verbose_name='آیدی پست')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='آیدی کاربر')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها ',
            },
        ),
        migrations.CreateModel(
            name='soundTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='عنوان')),
                ('artists', models.CharField(max_length=300, verbose_name='آرتیست ها')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ  انتشار')),
                ('image', models.ImageField(help_text=' Image file must be lowerthan 200kb, preferably 100kb , Use it in WEBP format and transparent', null=True, upload_to='images/', verbose_name='کاور آلبوم')),
                ('audioFile', models.FileField(upload_to='music/', verbose_name='فایل موسیقی')),
                ('fileSize', models.FloatField(blank=True, null=True, verbose_name='حجم فایل')),
                ('album', models.CharField(max_length=300, verbose_name='آلبوم')),
            ],
            options={
                'verbose_name': 'ساندترک',
                'verbose_name_plural': 'ساندترک ها',
            },
        ),
        migrations.CreateModel(
            name='soundTracksTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundTrackTags', models.CharField(max_length=70, verbose_name='تگ موسیقی')),
            ],
            options={
                'verbose_name': 'تگ موسیقی',
                'verbose_name_plural': 'تگ های موسیقی',
            },
        ),
        migrations.CreateModel(
            name='updatePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPassword', models.CharField(max_length=150)),
                ('newPassword', models.CharField(max_length=150)),
                ('confirmNewPassword', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='updateUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentUsername', models.CharField(max_length=150)),
                ('newUsername', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='wallpapersTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpapersTags', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ های والپیپر',
            },
        ),
        migrations.CreateModel(
            name='wallpapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='آدرس')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ  انتشار')),
                ('thumbnail', models.ImageField(help_text=' Image file must be lowerthan 200kb, preferably 100kb , Use it in WEBP format and transparent', upload_to='images/', verbose_name='تصویر تک صفحه')),
                ('device', models.CharField(blank=True, choices=[('desktop', 'دسکتاپ'), ('mobile', 'موبایل')], max_length=60, null=True, verbose_name='نوع دستگاه ')),
                ('image', models.ImageField(help_text=' Image file must belowerthan 200kb, preferably 100kb , Use it in WEBP format', null=True, upload_to='wallpapers/', verbose_name='فایل والپیپر')),
                ('resolution', models.CharField(blank=True, choices=[('normal', 'کیفیت معمولی'), ('highResolution', 'کیفیت عالی')], max_length=50, null=True, verbose_name='کیفیت')),
                ('tags', models.ManyToManyField(blank=True, to='blog.wallpaperstags', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'والپیپر',
                'verbose_name_plural': 'والپیپرها',
            },
        ),
        migrations.CreateModel(
            name='commentsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.comments', verbose_name='آیدی کامنت')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentLikes', to=settings.AUTH_USER_MODEL, verbose_name='آیدی کاربر')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک کامنت ها',
            },
        ),
        migrations.AddField(
            model_name='allposts',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=70, to='blog.allpoststags', verbose_name='تگ ها'),
        ),
        migrations.CreateModel(
            name='albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='عنوان')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ  انتشار')),
                ('image', models.ImageField(help_text=' Image file must be lowerthan 200kb, preferably 100kb , Use it in WEBP format and transparent', null=True, upload_to='images/', verbose_name='کاور آلبوم')),
                ('totalFileSize', models.FloatField(blank=True, null=True, verbose_name='حجم فایل')),
                ('zipFile', models.FileField(upload_to='zipfiles/', verbose_name='فایل زیپ')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='متن توضیحی')),
                ('platforms', models.ManyToManyField(blank=True, to='blog.albumplatforms')),
                ('soundTracks', models.ManyToManyField(to='blog.soundtracks', verbose_name='ساندترک ها')),
                ('tags', models.ManyToManyField(to='blog.albumstags', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': ' آلبوم موسیقی ها',
            },
        ),
    ]
