# Generated by Django 4.2.5 on 2023-11-19 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allposts',
            name='date',
        ),
        migrations.AddField(
            model_name='allposts',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
